const WORKFLOWS={
  enquiries:{label:'Enquiries & proposals',stages:['New','Under review','Awaiting Occono','Proposal preparation','Proposal sent','Waiting on customer','Accepted','Closed']},
  outreach:{label:'Outreach',stages:['Prospect found','Qualified','Outreach ready','Contacted','Follow-up','Engaged','Converted']},
  delivery:{label:'Build & delivery',stages:['Ready to start','In progress','Waiting','Review','Ready to launch','Complete']}
};
const CONTACT_OUTCOMES=[['spoke','Spoke to customer'],['no_answer','No answer'],['left_voicemail','Left voicemail'],['awaiting_information','Awaiting information'],['ready_discovery','Ready for discovery'],['not_suitable','Not suitable']];
let session=null;
const state={records:[],workflow:'all',owner:'all',attention:'all',source:'unknown',warning:null,saving:new Set()};
const board=document.querySelector('#board');
const workflowFilter=document.querySelector('#workflowFilter');
const ownerFilter=document.querySelector('#ownerFilter');
const ownerFilterWrap=document.querySelector('#ownerFilterWrap');
const attentionFilters=document.querySelector('#attentionFilters');
async function requestJson(url,options={}){const response=await fetch(url,{credentials:'same-origin',headers:{Accept:'application/json',...(options.body?{'Content-Type':'application/json'}:{})},...options});const payload=await response.json().catch(()=>({}));if(response.status===401){location.assign('/cdn-cgi/access/login');throw new Error('Authentication required');}if(!response.ok)throw new Error(payload.error||`Request failed (${response.status})`);return payload;}
const getJson=url=>requestJson(url);const patchJson=(url,body)=>requestJson(url,{method:'PATCH',body:JSON.stringify(body)});const postJson=(url,body)=>requestJson(url,{method:'POST',body:JSON.stringify(body)});
function esc(value=''){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function canonicalStage(workflow,value){const stages=WORKFLOWS[workflow]?.stages||[];const normalised=String(value||'').trim().replace(/\s+/g,' ').toLowerCase();return stages.find(stage=>stage.toLowerCase()===normalised)||'';}
function normaliseRecord(record){const status=canonicalStage(record.workflow,record.status);return {...record,status:status||String(record.status||'').trim(),unrecognisedStatus:status?'':String(record.status||'').trim()||'Blank status'};}
function applyWorkflowPayload(payload){state.records=(payload.records||[]).map(normaliseRecord);state.source=payload.source||state.source;state.warning=payload.warning||null;}
async function loadData(){try{const[sessionPayload,workflowPayload]=await Promise.all([getJson('/api/session'),getJson('/api/workflows')]);session=sessionPayload;applyWorkflowPayload(workflowPayload);}catch(error){console.error(error);board.innerHTML='<section class="load-error"><h2>Workflow unavailable</h2><p>The protected workflow data could not be loaded. Refresh the page or sign in again.</p></section>';throw error;}}
function initialiseFilters(){workflowFilter.innerHTML=`<option value="all">All workflows</option>${Object.entries(WORKFLOWS).map(([id,w])=>`<option value="${id}">${w.label}</option>`).join('')}`;refreshOwnerFilter();ownerFilterWrap.hidden=session.role!=='owner';workflowFilter.addEventListener('change',e=>{state.workflow=e.target.value;render();});ownerFilter.addEventListener('change',e=>{state.owner=e.target.value;render();});attentionFilters.addEventListener('click',e=>{const button=e.target.closest('[data-attention]');if(!button)return;state.attention=button.dataset.attention;render();});}
function refreshOwnerFilter(){const selected=state.owner,owners=[...new Set(state.records.map(r=>r.ownerName).filter(name=>name&&name!=='Unassigned'))].sort();ownerFilter.innerHTML=`<option value="all">Everyone</option>${owners.map(o=>`<option value="${esc(o)}">${esc(o)}</option>`).join('')}`;ownerFilter.value=owners.includes(selected)?selected:'all';state.owner=ownerFilter.value;}
function baseFiltered(){return state.records.filter(r=>(state.workflow==='all'||r.workflow===state.workflow)&&(state.owner==='all'||r.ownerName===state.owner));}
function isSameLocalDay(value,date=new Date()){if(!value)return false;const d=new Date(value);return!Number.isNaN(d.getTime())&&d.getFullYear()===date.getFullYear()&&d.getMonth()===date.getMonth()&&d.getDate()===date.getDate();}
function isOverdue(value){return Boolean(value)&&new Date(value)<new Date()&&!isSameLocalDay(value);}
function isDueToday(value){return isSameLocalDay(value);}
function exceptionFlags(record){const flags=[];if(record.unrecognisedStatus)flags.push(`Unrecognised status: ${record.unrecognisedStatus}`);if(!record.ownerId||!record.ownerName||record.ownerName==='Unassigned')flags.push('Missing owner');if(!String(record.nextAction||'').trim())flags.push('Missing action');if(!record.due)flags.push('Missing due date');return flags;}
function attentionMatch(record){if(state.attention==='exceptions')return exceptionFlags(record).length>0;if(state.attention==='overdue')return isOverdue(record.due);if(state.attention==='today')return isDueToday(record.due);return true;}
function dueRank(record){if(!record.due)return Number.POSITIVE_INFINITY;const time=new Date(record.due).getTime();return Number.isNaN(time)?Number.POSITIVE_INFINITY:time;}
function sortRecords(records){return[...records].sort((a,b)=>{const ae=exceptionFlags(a).length?1:0,be=exceptionFlags(b).length?1:0;if(ae!==be)return be-ae;const ad=dueRank(a),bd=dueRank(b);if(ad!==bd)return ad-bd;return String(a.title||a.id).localeCompare(String(b.title||b.id),'en-GB');});}
function filtered(){return sortRecords(baseFiltered().filter(attentionMatch));}
function stagesForView(records){if(state.workflow!=='all')return [...WORKFLOWS[state.workflow].stages,...(records.some(r=>r.workflow===state.workflow&&r.unrecognisedStatus)?['Unrecognised status']:[])];const visible=[];Object.entries(WORKFLOWS).forEach(([key,w])=>w.stages.forEach(stage=>{if(records.some(r=>r.workflow===key&&r.status===stage))visible.push(stage);}));if(records.some(r=>r.unrecognisedStatus))visible.push('Unrecognised status');return [...new Set(visible)];}
function formatDue(value){if(!value)return'No due date';const d=new Date(value);if(Number.isNaN(d.getTime()))return String(value);const prefix=isOverdue(value)?'Overdue · ':isDueToday(value)?'Today · ':'';return prefix+new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}).format(d);}
function dueClass(value){if(isOverdue(value))return'overdue';if(isDueToday(value))return'due-today';return'';}
function localInput(value){if(!value)return'';const d=new Date(value);if(Number.isNaN(d.getTime()))return'';const pad=n=>String(n).padStart(2,'0');return`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`;}
function safePhone(value){return String(value||'').split('/')[0].replace(/[^+\d]/g,'');}
function safeWebsite(value){const raw=String(value||'').trim();return/^https?:\/\//i.test(raw)?raw:'';}
function nextWorkingDue(){const d=new Date();d.setDate(d.getDate()+1);while(d.getDay()===0||d.getDay()===6)d.setDate(d.getDate()+1);d.setHours(9,0,0,0);return localInput(d.toISOString());}
function renderMetrics(records){const overdue=records.filter(r=>isOverdue(r.due)).length,today=records.filter(r=>isDueToday(r.due)).length,exceptions=records.filter(r=>exceptionFlags(r).length).length;document.querySelector('#metrics').innerHTML=[['Active',records.length],['Overdue',overdue],['Due today',today],['Exceptions',exceptions]].map(([label,value])=>`<article class="metric${((label==='Exceptions'||label==='Overdue')&&value)?' metric-alert':''}"><strong>${value}</strong><span>${label}</span></article>`).join('');}
function renderAttentionFilters(records){const counts={all:records.length,exceptions:records.filter(r=>exceptionFlags(r).length).length,overdue:records.filter(r=>isOverdue(r.due)).length,today:records.filter(r=>isDueToday(r.due)).length};attentionFilters.querySelectorAll('[data-attention]').forEach(button=>{button.classList.toggle('is-active',button.dataset.attention===state.attention);const labels={all:'All work',exceptions:'Needs attention',overdue:'Overdue',today:'Due today'};button.textContent=`${labels[button.dataset.attention]} · ${counts[button.dataset.attention]}`;});}
function recordInStage(record,stage){return stage==='Unrecognised status'?Boolean(record.unrecognisedStatus):record.status===stage;}
function render(){const base=baseFiltered(),records=filtered();renderMetrics(base);renderAttentionFilters(base);workflowFilter.value=state.workflow;document.querySelector('#userBadge').textContent=`${session.name} · ${session.role}`;document.querySelector('#pageTitle').textContent=session.role==='owner'?'All current work':'My assigned work';const baseText=session.role==='owner'?'Live operational view across Occono workflows.':'Only work assigned to your account is shown.';const connected=state.source!=='protected-demo'&&state.source!=='unknown',label=connected?`Connected to ${state.source}`:'Protected demo fallback',view=state.attention!=='all'?` Showing ${records.length} filtered record${records.length===1?'':'s'}.`:'',warning=state.warning?` — ${state.warning}`:'';document.querySelector('#pageSummary').textContent=`${baseText} ${label}.${view}${warning}`;const stages=stagesForView(records);board.innerHTML=stages.length?stages.map(stage=>{const cards=records.filter(r=>recordInStage(r,stage));return`<section class="column${stage==='Unrecognised status'?' column-exception':''}" data-stage="${esc(stage)}"><header class="column-header"><h2>${esc(stage)}</h2><span class="count">${cards.length}</span></header><div class="card-list">${cards.length?cards.map(cardTemplate).join(''):'<div class="empty">No matching work</div>'}</div></section>`;}).join(''):'<section class="filtered-empty"><h2>No matching work</h2><p>Nothing currently matches this attention filter.</p><button type="button" class="button clear-filter-button">Show all work</button></section>';attachBoardEvents();document.querySelector('.clear-filter-button')?.addEventListener('click',()=>{state.attention='all';render();});}
function cardTemplate(r){const saving=state.saving.has(r.id),flags=exceptionFlags(r);return`<article class="work-card${saving?' saving':''}${flags.length?' has-exception':''}" draggable="${session.role==='owner'&&!saving}" data-id="${esc(r.id)}"><span class="card-id">${esc(r.id)} · ${esc(WORKFLOWS[r.workflow].label)}</span><h3>${esc(r.title)}</h3><div class="card-meta">${esc(r.contact)}</div>${flags.length?`<div class="exception-flags">${flags.map(flag=>`<span>${esc(flag)}</span>`).join('')}</div>`:''}<div class="card-footer"><span>${saving?'Working…':esc(r.ownerName||'Unassigned')}</span><span class="${dueClass(r.due)}">${esc(formatDue(r.due))}</span></div></article>`;}
function attachBoardEvents(){document.querySelectorAll('.work-card').forEach(card=>{card.addEventListener('click',()=>openCard(card.dataset.id));card.addEventListener('dragstart',e=>e.dataTransfer.setData('text/plain',card.dataset.id));});if(session.role!=='owner')return;document.querySelectorAll('.column:not(.column-exception)').forEach(column=>{column.addEventListener('dragover',e=>{e.preventDefault();column.classList.add('drop-target');});column.addEventListener('dragleave',()=>column.classList.remove('drop-target'));column.addEventListener('drop',async e=>{e.preventDefault();column.classList.remove('drop-target');await saveChanges(e.dataTransfer.getData('text/plain'),{status:column.dataset.stage});});});}
async function saveChanges(id,changes){const record=state.records.find(r=>r.id===id);if(!record||state.saving.has(id))return;if(changes.status){const canonical=canonicalStage(record.workflow,changes.status);if(!canonical)throw new Error('The selected status is not valid for this workflow.');changes.status=canonical;}const previous={...record};Object.assign(record,normaliseRecord({...record,...changes}));state.saving.add(id);render();try{await patchJson('/api/workflows',{id:record.id,workflow:record.workflow,changes});const payload=await getJson('/api/workflows');applyWorkflowPayload(payload);const refreshed=state.records.find(r=>r.id===id);if(!refreshed)throw new Error('The saved record was not returned by the workflow API.');state.warning=`${id} saved in ${refreshed.unrecognisedStatus?'Unrecognised status':refreshed.status}.`;refreshOwnerFilter();}catch(error){Object.assign(record,previous);state.warning=`Change not saved: ${error.message}`;console.error(error);}finally{state.saving.delete(id);render();}}
function promotionFor(record){if(record.workflow==='outreach'&&record.status==='Converted')return{label:'Move to enquiries',target:'Enquiries & proposals'};if(record.workflow==='enquiries'&&record.status==='Accepted')return{label:'Move to build & delivery',target:'Build & delivery'};return null;}
async function promoteRecord(id){const record=state.records.find(r=>r.id===id);if(!record||state.saving.has(id))return;const button=document.querySelector('#handoffButton'),dialog=document.querySelector('#cardDialog');if(button){button.disabled=true;button.textContent='Moving…';}state.saving.add(id);state.warning=`Moving ${record.id} to the next workflow…`;if(dialog.open)dialog.close();render();try{const result=await postJson('/api/workflows',{id:record.id,workflow:record.workflow}),target=result.promotion?.targetWorkflow||'all',destination=result.promotion?.record;if(destination){const defaults={};if(!destination.ownerId||destination.ownerName==='Unassigned'){defaults.ownerName='Darren';defaults.ownerEmail='darren@occono.co.uk';}if(!String(destination.nextAction||'').trim())defaults.nextAction=target==='delivery'?'Complete project setup':'Review promoted enquiry';if(!destination.due)defaults.due=nextWorkingDue();if(Object.keys(defaults).length)await patchJson('/api/workflows',{id:destination.id,workflow:target,changes:defaults});}const payload=await getJson('/api/workflows');applyWorkflowPayload(payload);state.workflow=target;state.attention='all';state.warning=`Moved successfully to ${result.promotion?.destinationId||'the next workflow'}.`;refreshOwnerFilter();}catch(error){state.warning=`Record not moved: ${error.message}`;console.error(error);}finally{state.saving.delete(id);render();}}
async function recordOutcome(id,outcome){const record=state.records.find(r=>r.id===id);if(!record||record.workflow!=='enquiries'||state.saving.has(id))return;const dialog=document.querySelector('#cardDialog');state.saving.add(id);state.warning=`Recording outcome for ${id}…`;if(dialog.open)dialog.close();render();try{const result=await postJson('/api/workflows',{action:'recordOutcome',id,workflow:'enquiries',outcome});const payload=await getJson('/api/workflows');applyWorkflowPayload(payload);state.warning=`${result.outcome} recorded for ${id}.`;refreshOwnerFilter();}catch(error){state.warning=`Outcome not recorded: ${error.message}`;console.error(error);}finally{state.saving.delete(id);render();}}
function contactPanel(r){if(r.workflow!=='enquiries')return'';const phone=safePhone(r.phone),website=safeWebsite(r.website),links=[r.email?`<a class="contact-link" href="mailto:${encodeURIComponent(r.email)}">Email customer</a>`:'',phone?`<a class="contact-link" href="tel:${phone}">Call customer</a>`:'',website?`<a class="contact-link" href="${esc(website)}" target="_blank" rel="noopener">Open website</a>`:''].filter(Boolean).join('');return`<section class="contact-panel"><div class="panel-heading"><strong>Customer contact</strong><span>${Number(r.followUpCount)||0} recorded follow-up${Number(r.followUpCount)===1?'':'s'}</span></div>${links?`<div class="contact-links">${links}</div>`:'<p>No contact links are available for this record.</p>'}<div class="contact-details">${r.email?`<span>${esc(r.email)}</span>`:''}${r.phone?`<span>${esc(r.phone)}</span>`:''}</div><div class="outcome-grid">${CONTACT_OUTCOMES.map(([key,label])=>`<button type="button" class="outcome-button${key==='not_suitable'?' outcome-negative':''}" data-outcome="${key}">${label}</button>`).join('')}</div></section>`;}
function overviewTab(r,editable,promotion,flags){return`${flags.length?`<div class="dialog-exceptions"><strong>Needs attention</strong>${flags.map(flag=>`<span>${esc(flag)}</span>`).join('')}</div>`:''}${editable?contactPanel(r):''}<form id="cardEditForm" class="card-edit"><label>Status<select name="status" ${editable?'':'disabled'}>${WORKFLOWS[r.workflow].stages.map(s=>`<option ${s===r.status?'selected':''}>${esc(s)}</option>`).join('')}</select></label><label>Assigned name<input name="ownerName" value="${esc(r.ownerName==='Unassigned'?'':r.ownerName)}" ${editable?'':'disabled'}></label><label>Assigned email<input name="ownerEmail" type="email" value="${esc(r.ownerEmail||'')}" ${editable?'':'disabled'}></label><label>Next action<input name="nextAction" value="${esc(r.nextAction||'')}" ${editable?'':'disabled'}></label><label>Due<input name="due" type="datetime-local" value="${esc(localInput(r.due))}" ${editable?'':'disabled'}></label>${editable?'<button type="submit" class="button save-button">Save changes</button>':''}</form>${promotion?`<section class="handoff-panel"><p><strong>${esc(promotion.target)}</strong><br>This record has reached its workflow handoff point.</p><button id="handoffButton" type="button" class="button handoff-button">${esc(promotion.label)}</button></section>`:''}`;}
function customerTab(r){return`<section class="crm-panel"><div class="crm-grid"><div><span>Contact</span><strong>${esc(r.contact||'Not recorded')}</strong></div><div><span>Business</span><strong>${esc(r.title||'Not recorded')}</strong></div><div><span>Primary email</span><strong>${esc(r.email||'Not recorded')}</strong></div><div><span>CC recipients</span><strong>${esc(r.ccEmails||'None')}</strong></div><div><span>Telephone</span><strong>${esc(r.phone||'Not recorded')}</strong></div><div><span>Website</span><strong>${r.website?`<a href="${esc(r.website)}" target="_blank" rel="noopener">Open website</a>`:'Not recorded'}</strong></div></div><p class="panel-note">This customer view is linked to the current enquiry. Related-enquiry history will be added when the customer relationship endpoint is enabled.</p></section>`;}
function formsTab(r){return`<section class="crm-panel"><article class="document-card"><div><span class="document-type">Enquiry form</span><h3>Original enquiry submission</h3><p>${esc(r.summary||'No submitted enquiry text is available.')}</p></div><span class="document-status">Received</span></article><article class="document-card document-muted"><div><span class="document-type">Discovery</span><h3>Discovery response and brief</h3><p>Linked discovery documents will appear here when present in the enquiry evidence register.</p></div><span class="document-status">Not linked</span></article></section>`;}
function timelineTab(r){const items=[{title:'Current position',detail:`${r.status}${r.nextAction?` · ${r.nextAction}`:''}`,actor:r.ownerName||'Unassigned',time:r.due?`Due ${formatDue(r.due)}`:'No due date'},{title:'Enquiry received',detail:r.summary||'Enquiry record created.',actor:r.contact||'Customer',time:'Start of record'}];return`<section class="crm-panel"><ol class="timeline">${items.map(item=>`<li><span class="timeline-marker"></span><div><strong>${esc(item.title)}</strong><p>${esc(item.detail)}</p><small>${esc(item.actor)} · ${esc(item.time)}</small></div></li>`).join('')}</ol><p class="panel-note">Communication, audit and form events will populate this view from the Activities and Kanban Audit registers.</p></section>`;}
function openCard(id){const r=state.records.find(x=>x.id===id);if(!r)return;const editable=session.role==='owner',promotion=editable?promotionFor(r):null,flags=exceptionFlags(r);document.querySelector('#cardDetails').innerHTML=`<p class="eyebrow">${esc(WORKFLOWS[r.workflow].label)}</p><h2>${esc(r.title)}</h2><p class="record-summary">${esc(r.summary)}</p><nav class="record-tabs" aria-label="Record sections"><button type="button" class="record-tab is-active" data-tab="overview">Overview</button><button type="button" class="record-tab" data-tab="customer">Customer</button><button type="button" class="record-tab" data-tab="forms">Forms & documents</button><button type="button" class="record-tab" data-tab="timeline">Timeline</button></nav><div class="record-tab-panel" data-panel="overview">${overviewTab(r,editable,promotion,flags)}</div><div class="record-tab-panel" data-panel="customer" hidden>${customerTab(r)}</div><div class="record-tab-panel" data-panel="forms" hidden>${formsTab(r)}</div><div class="record-tab-panel" data-panel="timeline" hidden>${timelineTab(r)}</div>`;document.querySelectorAll('.record-tab').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.record-tab').forEach(tab=>tab.classList.toggle('is-active',tab===button));document.querySelectorAll('.record-tab-panel').forEach(panel=>panel.hidden=panel.dataset.panel!==button.dataset.tab);}));document.querySelector('#cardEditForm')?.addEventListener('submit',async e=>{e.preventDefault();const data=new FormData(e.currentTarget);document.querySelector('#cardDialog').close();await saveChanges(id,{status:data.get('status'),ownerName:String(data.get('ownerName')||'').trim(),ownerEmail:String(data.get('ownerEmail')||'').trim().toLowerCase(),nextAction:String(data.get('nextAction')||'').trim(),due:data.get('due')});});document.querySelectorAll('[data-outcome]').forEach(button=>button.addEventListener('click',()=>recordOutcome(id,button.dataset.outcome)));document.querySelector('#handoffButton')?.addEventListener('click',()=>promoteRecord(id));document.querySelector('#cardDialog').showModal();}
document.querySelector('#dialogCloseButton').addEventListener('click',()=>document.querySelector('#cardDialog').close());document.querySelector('#cardDialog').addEventListener('click',event=>{if(event.target===event.currentTarget)event.currentTarget.close();});document.querySelector('#logoutButton').addEventListener('click',()=>location.assign('/cdn-cgi/access/logout'));loadData().then(()=>{initialiseFilters();render();});