const CONFIG = Object.freeze({
  apiTokenProperty: 'KANBAN_API_TOKEN', environment: 'TEST', auditSheetName: 'Kanban Audit', overrideSheetName: 'Kanban Overrides', handoffSheetName: 'Workflow Handoffs',
  sources: Object.freeze({
    enquiries:{spreadsheetId:'1BqRdcKQ-xLZksS-fe0zc6nD-L364JpmImtu-JmGX2YM',sheetName:'Enquiries',idColumn:'Enquiry ID'},
    outreach:{spreadsheetId:'1OPgKuBAmISSpcEisZtkQFmsq_b8Fvj8ldmSnj8xvV1c',sheetName:'Prospects',idColumn:'Prospect ID'},
    delivery:{spreadsheetId:'11lUo6o86mrwhTzVwt0l72WH1wZ8NFhldPW5lCClPquE',sheetName:'Projects',idColumn:'Project ID'},
  }),
  stages:Object.freeze({enquiries:['New','Under review','Awaiting Occono','Proposal preparation','Proposal sent','Waiting on customer','Accepted','Closed'],outreach:['Prospect found','Qualified','Outreach ready','Contacted','Follow-up','Engaged','Converted'],delivery:['Ready to start','In progress','Waiting','Review','Ready to launch','Complete']}),
});

function doPost(e){try{const body=JSON.parse((e&&e.postData&&e.postData.contents)||'{}');assertAuthorised_(body.token);if(body.action==='listWorkflows')return listWorkflows_();if(body.action==='updateRecord')return updateRecord_(body);if(body.action==='createHandoff')return createHandoff_(body);return json_({ok:false,error:'Unsupported action.'},400)}catch(error){console.error(error);return json_({ok:false,error:error.message||'Unexpected error.'},500)}}
function listWorkflows_(){return json_({ok:true,environment:CONFIG.environment,source:'Occono TEST and DEVELOPMENT workflow workbooks',generatedAt:new Date().toISOString(),records:[].concat(readEnquiries_(),readOutreach_(),readDelivery_())},200)}

function updateRecord_(body){const workflow=String(body.workflow||'').trim(),id=String(body.id||'').trim(),actorEmail=String(body.actorEmail||'').trim().toLowerCase(),changes=body.changes||{};if(!(workflow in CONFIG.sources))throw new Error('Unknown workflow.');if(!id)throw new Error('Record ID is required.');if(!actorEmail)throw new Error('Actor email is required.');const allowed=['status','ownerName','ownerEmail','nextAction','due'];const keys=Object.keys(changes).filter(k=>allowed.includes(k));if(!keys.length)throw new Error('No supported changes supplied.');if('status'in changes&&!CONFIG.stages[workflow].includes(String(changes.status)))throw new Error('Invalid workflow stage.');const lock=LockService.getScriptLock();lock.waitLock(10000);try{const source=CONFIG.sources[workflow],spreadsheet=SpreadsheetApp.openById(source.spreadsheetId),sheet=spreadsheet.getSheetByName(source.sheetName);if(!sheet)throw new Error(`${source.sheetName} sheet not found.`);const values=sheet.getDataRange().getDisplayValues(),headers=values[0]||[],column=Object.fromEntries(headers.map((h,i)=>[h,i]));const rowIndex=values.findIndex((row,index)=>index>0&&row[column[source.idColumn]]===id);if(rowIndex<1)throw new Error(`Record not found: ${id}`);const before=findRecord_(workflow,id);if('status'in changes)applyStatus_(workflow,sheet,rowIndex+1,column,String(changes.status));const overrideChanges={};['ownerName','ownerEmail','nextAction','due'].forEach(k=>{if(k in changes)overrideChanges[k]=String(changes[k]||'').trim()});if(Object.keys(overrideChanges).length)upsertOverrides_(spreadsheet,id,overrideChanges);SpreadsheetApp.flush();const after=findRecord_(workflow,id);keys.forEach(key=>appendAudit_(spreadsheet,{actorEmail,id,workflow,field:key,oldValue:before[key]||'',newValue:after[key]||''}));return json_({ok:true,source:'Occono TEST and DEVELOPMENT workflow workbooks',record:after},200)}finally{lock.releaseLock()}}

function createHandoff_(body){const workflow=String(body.workflow||'').trim(),id=String(body.id||'').trim(),actorEmail=String(body.actorEmail||'').trim().toLowerCase();if(!id||!actorEmail)throw new Error('Record ID and actor email are required.');const record=findRecord_(workflow,id);let targetKey,targetLabel;if(workflow==='outreach'&&record.status==='Converted'){targetKey='enquiries';targetLabel='Enquiries & proposals'}else if(workflow==='enquiries'&&record.status==='Accepted'){targetKey='delivery';targetLabel='Build & delivery'}else{throw new Error('This record is not eligible for a handoff.')}const targetSpreadsheet=SpreadsheetApp.openById(CONFIG.sources[targetKey].spreadsheetId);let sheet=targetSpreadsheet.getSheetByName(CONFIG.handoffSheetName);if(!sheet){sheet=targetSpreadsheet.insertSheet(CONFIG.handoffSheetName);sheet.appendRow(['Handoff ID','Created Timestamp','Source Workflow','Source Record ID','Target Workflow','Business / Project','Contact','Summary','Owner Name','Owner Email','Status','Actor Email','Environment']);sheet.setFrozenRows(1)}const values=sheet.getDataRange().getDisplayValues();const existing=values.find((row,index)=>index>0&&row[2]===workflow&&row[3]===id&&row[4]===targetKey&&row[10]!=='Cancelled');if(existing)throw new Error(`An active handoff already exists: ${existing[0]}`);const handoffId=nextHandoffId_(values);sheet.appendRow([handoffId,new Date(),workflow,id,targetKey,record.title||'',record.contact||'',record.summary||'',record.ownerName||'',record.ownerEmail||'','Pending review',actorEmail,CONFIG.environment]);appendAudit_(targetSpreadsheet,{actorEmail,id,workflow,field:'Handoff',oldValue:'',newValue:`${handoffId} → ${targetLabel}`});return json_({ok:true,source:'Occono TEST and DEVELOPMENT workflow workbooks',handoff:{id:handoffId,target:targetLabel,status:'Pending review'}},200)}
function nextHandoffId_(values){const year=new Date().getFullYear(),max=values.slice(1).map(r=>String(r[0]||'')).map(v=>{const m=v.match(/^HOF-(\d{4})-(\d+)$/);return m&&Number(m[1])===year?Number(m[2]):0}).reduce((a,b)=>Math.max(a,b),0);return`HOF-${year}-${String(max+1).padStart(4,'0')}`}

function applyStatus_(workflow,sheet,rowNumber,column,status){if(workflow==='enquiries'){requireColumns_(column,['Status']);sheet.getRange(rowNumber,column['Status']+1).setValue(status);return}if(workflow==='outreach'){requireColumns_(column,['Current Status']);const values={'Prospect found':'Prospect found','Qualified':'Qualified','Outreach ready':'Qualified — draft awaiting approval','Contacted':'Contacted — awaiting response','Follow-up':'Follow-up due','Engaged':'Engaged','Converted':'Converted'};sheet.getRange(rowNumber,column['Current Status']+1).setValue(values[status]);return}requireColumns_(column,['Status','Current Phase']);const values={'Ready to start':['Ready to start','Ready to start'],'In progress':['Active','In progress'],'Waiting':['Active','Waiting'],'Review':['Active','Review'],'Ready to launch':['Active','Ready to launch'],'Complete':['Complete','Delivered']};const [projectStatus,phase]=values[status];sheet.getRange(rowNumber,column['Status']+1).setValue(projectStatus);sheet.getRange(rowNumber,column['Current Phase']+1).setValue(phase)}
function overrides_(spreadsheet){const sheet=spreadsheet.getSheetByName(CONFIG.overrideSheetName);if(!sheet)return{};const values=sheet.getDataRange().getDisplayValues();if(values.length<2)return{};const [headers,...rows]=values,column=Object.fromEntries(headers.map((h,i)=>[h,i]));return Object.fromEntries(rows.filter(r=>r[column['Record ID']]).map(r=>[r[column['Record ID']],{ownerName:r[column['Owner Name']]||'',ownerEmail:(r[column['Owner Email']]||'').toLowerCase(),nextAction:r[column['Next Action']]||'',due:r[column['Due']]||''}]))}
function upsertOverrides_(spreadsheet,id,changes){let sheet=spreadsheet.getSheetByName(CONFIG.overrideSheetName);if(!sheet){sheet=spreadsheet.insertSheet(CONFIG.overrideSheetName);sheet.appendRow(['Record ID','Owner Name','Owner Email','Next Action','Due','Updated Timestamp']);sheet.setFrozenRows(1)}const values=sheet.getDataRange().getDisplayValues(),rowIndex=values.findIndex((r,i)=>i>0&&r[0]===id),current=rowIndex>0?values[rowIndex]:[id,'','','','',''];const merged=[id,changes.ownerName!==undefined?changes.ownerName:current[1],changes.ownerEmail!==undefined?changes.ownerEmail:current[2],changes.nextAction!==undefined?changes.nextAction:current[3],changes.due!==undefined?changes.due:current[4],new Date()];if(rowIndex>0)sheet.getRange(rowIndex+1,1,1,6).setValues([merged]);else sheet.appendRow(merged)}
function appendAudit_(spreadsheet,entry){let sheet=spreadsheet.getSheetByName(CONFIG.auditSheetName);if(!sheet){sheet=spreadsheet.insertSheet(CONFIG.auditSheetName);sheet.appendRow(['Timestamp','Actor Email','Record ID','Workflow','Field','Old Value','New Value','Environment','Source']);sheet.setFrozenRows(1)}sheet.appendRow([new Date(),entry.actorEmail,entry.id,entry.workflow,entry.field,entry.oldValue,entry.newValue,CONFIG.environment,'Workflow Kanban'])}
function assertAuthorised_(providedToken){const expected=PropertiesService.getScriptProperties().getProperty(CONFIG.apiTokenProperty);if(!expected)throw new Error('KANBAN_API_TOKEN is not configured.');if(!providedToken||providedToken!==expected)throw new Error('Unauthorised.')}
function readTable_(key){const source=CONFIG.sources[key],spreadsheet=SpreadsheetApp.openById(source.spreadsheetId),sheet=spreadsheet.getSheetByName(source.sheetName);if(!sheet)throw new Error(`${source.sheetName} sheet not found.`);const values=sheet.getDataRange().getDisplayValues();if(values.length<2)return{spreadsheet,column:{},rows:[]};const headers=values.shift();return{spreadsheet,column:Object.fromEntries(headers.map((h,i)=>[h,i])),rows:values}}
function requireColumns_(column,names){names.forEach(name=>{if(!(name in column))throw new Error(`Required column missing: ${name}`)})}
function owner_(value){const ownerName=String(value||'').trim(),ownerEmail=/\bdarren\b/i.test(ownerName)?'darren@occono.co.uk':'';return{ownerId:ownerEmail?`email:${ownerEmail}`:'',ownerEmail,ownerName:ownerName||'Unassigned'}}
function applyOverride_(record,override){if(!override)return record;const ownerEmail=override.ownerEmail||record.ownerEmail||'',ownerName=override.ownerName||record.ownerName||'Unassigned';return{...record,ownerEmail,ownerName,ownerId:ownerEmail?`email:${ownerEmail}`:'',nextAction:override.nextAction!==''?override.nextAction:record.nextAction,due:override.due!==''?override.due:record.due}}
function readEnquiries_(){const{spreadsheet,column,rows}=readTable_('enquiries'),over=overrides_(spreadsheet);requireColumns_(column,['Enquiry ID','Name','Business','Original Message','Status','Owner','Next Action','Next Action Due']);return rows.filter(r=>r[column['Enquiry ID']]).map(r=>applyOverride_({id:r[column['Enquiry ID']],workflow:'enquiries',title:r[column['Business']]||r[column['Name']]||r[column['Enquiry ID']],contact:r[column['Name']]||'',status:mapEnquiryStatus_(r[column['Status']]),...owner_(r[column['Owner']]),nextAction:r[column['Next Action']]||'',due:r[column['Next Action Due']]||'',summary:r[column['Original Message']]||''},over[r[column['Enquiry ID']]]))}
function readOutreach_(){const{spreadsheet,column,rows}=readTable_('outreach'),over=overrides_(spreadsheet);requireColumns_(column,['Prospect ID','Business Name','Current Status','Owner','Next Follow-up','Notes']);return rows.filter(r=>r[column['Prospect ID']]).map(r=>applyOverride_({id:r[column['Prospect ID']],workflow:'outreach',title:r[column['Business Name']]||r[column['Prospect ID']],contact:r[column['Contact Name']]||r[column['Town / Area']]||'',status:mapOutreachStatus_(r[column['Current Status']]),...owner_(r[column['Owner']]),nextAction:outreachNextAction_(r[column['Current Status']],r[column['Preferred Channel']]),due:r[column['Next Follow-up']]||'',summary:r[column['Notes']]||''},over[r[column['Prospect ID']]]))}
function readDelivery_(){const{spreadsheet,column,rows}=readTable_('delivery'),over=overrides_(spreadsheet);requireColumns_(column,['Project ID','Project Name','Business Name','Status','Current Phase','Owner','Target Delivery','Notes']);return rows.filter(r=>r[column['Project ID']]).map(r=>applyOverride_({id:r[column['Project ID']],workflow:'delivery',title:r[column['Project Name']]||r[column['Business Name']]||r[column['Project ID']],contact:r[column['Business Name']]||'',status:mapDeliveryStatus_(r[column['Status']],r[column['Current Phase']]),...owner_(r[column['Owner']]),nextAction:r[column['Current Phase']]||r[column['Status']]||'',due:r[column['Target Delivery']]||'',summary:r[column['Notes']]||''},over[r[column['Project ID']]]))}
function findRecord_(workflow,id){const readers={enquiries:readEnquiries_,outreach:readOutreach_,delivery:readDelivery_},record=readers[workflow]&&readers[workflow]().find(item=>item.id===id);if(!record)throw new Error('Record could not be found.');return record}
function mapEnquiryStatus_(v){return String(v||'').trim()||'New'}
function mapOutreachStatus_(v){const s=String(v||'').toLowerCase();if(s.includes('converted'))return'Converted';if(s.includes('engaged')||s.includes('interested'))return'Engaged';if(s.includes('follow'))return'Follow-up';if(s.includes('contacted')||s.includes('awaiting response'))return'Contacted';if(s.includes('draft'))return'Outreach ready';if(s.includes('qualified'))return'Qualified';return'Prospect found'}
function outreachNextAction_(s,c){s=String(s||'');c=String(c||'');if(/awaiting response/i.test(s))return'Review response or follow up';if(/draft awaiting approval/i.test(s))return`Review ${c||'outreach'} draft`;if(/draft blocked/i.test(s))return'Resolve blocked draft';return s||'Review prospect'}
function mapDeliveryStatus_(s,p){const c=`${s||''} ${p||''}`.toLowerCase();if(c.includes('closed')||c.includes('complete')||c.includes('delivered'))return'Complete';if(c.includes('launch'))return'Ready to launch';if(c.includes('review'))return'Review';if(c.includes('waiting')||c.includes('blocked'))return'Waiting';if(c.includes('progress')||c.includes('build'))return'In progress';return'Ready to start'}
function json_(payload,status){return ContentService.createTextOutput(JSON.stringify({...payload,status})).setMimeType(ContentService.MimeType.JSON)}
